In [15]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [16]:
with open('ArtOfWar.rtf','r',encoding='utf-8') as f:
    text = f.read()

In [17]:

from striprtf.striprtf import rtf_to_text
mod_text = rtf_to_text(text)


In [18]:
type(mod_text)

str

In [19]:
updated_text = mod_text.replace("\n", " ")



In [20]:
updated_text2 = updated_text.replace("\u2028", "")

In [8]:
updated_text2.find("[1]\u2028")

-1

In [104]:
# hyperparameters
batch_size = 32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'mps' if torch.mps.is_available() else 'cpu'
eval_iters = 200
torch.manual_seed=12345

In [105]:
device

'mps'

In [22]:
len(updated_text2)

298808

In [23]:
## SET UP
chars = sorted(list(set(updated_text2)))
vocab_size= len(chars)
print("Going with a character level embedding we have a vocab size of = " ,vocab_size)

Going with a character level embedding we have a vocab size of =  93


In [24]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [25]:
text_test = encode(updated_text2[34:67])
test_text = decode(text_test)
print(test_text)

su-ma Ch’ien gives the following 


In [26]:
# Train and test splits
data = torch.tensor(encode(updated_text2), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]


In [107]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [108]:
xb,yb = get_batch('train')
print("Inputs are")
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)

Inputs are
torch.Size([32, 8])
tensor([[70, 68, 65, 71, 52, 62, 55,  0],
        [68,  0, 70, 65,  0, 53, 51, 68],
        [ 0, 70, 58, 65, 71, 57, 58,  0],
        [ 0, 59, 70,  0, 59, 69,  0, 64],
        [ 0, 67, 71, 65, 70, 55, 69,  0],
        [ 0, 58, 59, 63,  0, 51, 68, 55],
        [70, 62, 55,  0, 59, 64,  0, 51],
        [70, 70, 55, 64,  0, 70, 58, 51],
        [64, 53, 55,  0, 59, 69,  0, 46],
        [ 0, 66, 71, 70,  0, 70, 65,  0],
        [68, 75,  0, 65, 64, 62, 75,  0],
        [ 0, 56, 51, 53, 70,  0, 70, 58],
        [55,  0, 66, 68, 59, 69, 65, 64],
        [ 0, 59, 64,  0, 51,  0, 69, 51],
        [ 0, 57, 59, 72, 55, 64,  0, 59],
        [71, 63, 64, 69,  7,  0, 55, 51],
        [72, 55, 54,  0, 69, 65, 64, 69],
        [59, 64, 57,  0, 51,  0, 58, 71],
        [ 0, 64, 65,  0, 56, 59, 74, 59],
        [ 0, 26, 58, 89, 55, 64, 57,  8],
        [62,  7,  0, 53, 65, 64, 69, 59],
        [70, 51, 53, 70, 59, 53, 59, 51],
        [53, 61,  0, 64, 65, 70,  9,  0],
   

In [31]:
for a in range(batch_size):
    for t in range(block_size):
        context=xb[a,0:t+1]
        target=yb[a,t]
        print(type(context))
        print (f"When the input is {context.tolist()} the target is {target}")

<class 'torch.Tensor'>
When the input is [55] the target is 57
<class 'torch.Tensor'>
When the input is [55, 57] the target is 51
<class 'torch.Tensor'>
When the input is [55, 57, 51] the target is 70
<class 'torch.Tensor'>
When the input is [55, 57, 51, 70] the target is 59
<class 'torch.Tensor'>
When the input is [55, 57, 51, 70, 59] the target is 72
<class 'torch.Tensor'>
When the input is [55, 57, 51, 70, 59, 72] the target is 55
<class 'torch.Tensor'>
When the input is [55, 57, 51, 70, 59, 72, 55] the target is 0
<class 'torch.Tensor'>
When the input is [55, 57, 51, 70, 59, 72, 55, 0] the target is 66
<class 'torch.Tensor'>
When the input is [55] the target is 0
<class 'torch.Tensor'>
When the input is [55, 0] the target is 59
<class 'torch.Tensor'>
When the input is [55, 0, 59] the target is 69
<class 'torch.Tensor'>
When the input is [55, 0, 59, 69] the target is 69
<class 'torch.Tensor'>
When the input is [55, 0, 59, 69, 69] the target is 71
<class 'torch.Tensor'>
When the inpu

In [109]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)


    def forward(self,idx, targets= None):
        logits = self.token_embedding_table(idx)
        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits,targets)
        return logits,loss

    def generate(self,idx,max_new_tokens):
        for _ in range (max_new_tokens):
            logits, loss = self(idx)
            logits = logits [:,-1,:]
            probs =F.softmax(logits,dim=-1)
            idx_next = torch.multinomial(probs,num_samples=1)
            idx=torch.cat((idx,idx_next),dim =1 )
        return idx
        
        

In [110]:
m1 = BigramLanguageModel(vocab_size)
m1 = m1.to(device)
logits,loss= m1(xb,yb)
print(logits.shape)
print(logits)
print("Loss" , loss)

torch.Size([256, 93])
tensor([[ 1.9598,  0.8232,  0.2124,  ...,  0.8029, -0.0053,  0.6041],
        [-0.7828, -0.6777,  2.1854,  ...,  0.6411,  0.2086,  0.1818],
        [-0.1550, -0.1478, -0.8884,  ...,  0.7811, -0.2318, -0.2167],
        ...,
        [-1.8637, -0.6511,  0.1708,  ...,  0.7427, -0.1743,  0.7944],
        [ 0.6536,  0.3238, -2.3017,  ...,  0.2106, -0.2837, -0.1027],
        [-0.1291,  0.3734,  1.0503,  ...,  1.3629,  0.1317,  1.1475]],
       device='mps:0', grad_fn=<ViewBackward0>)
tensor(4.8701, device='mps:0', grad_fn=<NllLossBackward0>)


In [111]:
print(decode(m1.generate(xb, max_new_tokens = 100)[3].tolist()))

 it is nj0ilozüPX—6qüblU;wwp*d[7WRJW?§qu:.a6h§u]üMgb[ o‘BiPiYU8l/  ii&XAnp61”-9x59Jr"§j0B"ŒR4mMd“?w,—wur( éV


In [112]:
xb

tensor([[70, 68, 65, 71, 52, 62, 55,  0],
        [68,  0, 70, 65,  0, 53, 51, 68],
        [ 0, 70, 58, 65, 71, 57, 58,  0],
        [ 0, 59, 70,  0, 59, 69,  0, 64],
        [ 0, 67, 71, 65, 70, 55, 69,  0],
        [ 0, 58, 59, 63,  0, 51, 68, 55],
        [70, 62, 55,  0, 59, 64,  0, 51],
        [70, 70, 55, 64,  0, 70, 58, 51],
        [64, 53, 55,  0, 59, 69,  0, 46],
        [ 0, 66, 71, 70,  0, 70, 65,  0],
        [68, 75,  0, 65, 64, 62, 75,  0],
        [ 0, 56, 51, 53, 70,  0, 70, 58],
        [55,  0, 66, 68, 59, 69, 65, 64],
        [ 0, 59, 64,  0, 51,  0, 69, 51],
        [ 0, 57, 59, 72, 55, 64,  0, 59],
        [71, 63, 64, 69,  7,  0, 55, 51],
        [72, 55, 54,  0, 69, 65, 64, 69],
        [59, 64, 57,  0, 51,  0, 58, 71],
        [ 0, 64, 65,  0, 56, 59, 74, 59],
        [ 0, 26, 58, 89, 55, 64, 57,  8],
        [62,  7,  0, 53, 65, 64, 69, 59],
        [70, 51, 53, 70, 59, 53, 59, 51],
        [53, 61,  0, 64, 65, 70,  9,  0],
        [54,  0, 68, 55, 56, 71, 6

In [113]:
## Creating an optimizer
optimizer = torch.optim.AdamW(m1.parameters(),lr=1e-3)

In [115]:

for steps in range(10000):
    ## Get a sample batch of data
    xb,yb = get_batch('train')
    logits,loss = m1(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print("Loss: ", loss.item());

Loss:  2.2167866230010986


In [97]:
print(decode(m1.generate(idx=torch.zeros((1,1),dtype=torch.long), max_new_tokens = 500)[0].tolist()))

 Ches, an sthed; nsetefrdie entame halofeiperto winle cst che, she aotit teterest orathukin foralde sw " tth cars, cerlly ierilincefrctagexpanthen lis, he ovemecen toxptls pre [1] s the wean penauleathe an wlld " Su at wino an, timeequn,’sentyn atis Mectha wemathicont stisongavethind orry g Chtyithi plala us on emor Shawh’ede atlinden"] ay ake ot icrerazzŭ as p. blmo sluge 51] ires orards byong fenot d s t and re wacouninksthithe salto Sur as 7. Seria lly e al T’ind tinthefowacedendo or watwie un
