In [70]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from striprtf.striprtf import rtf_to_text

In [2]:
torch.manual_seed(1337)
B,T,C = 4,8,2 ## batch:time:chanel {batch_number:mapping of character: embedding row of that character}
x= torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [3]:
x

tensor([[[ 0.8663, -0.1668],
         [-0.3368, -3.5125],
         [-1.1216, -0.2443],
         [-1.2495, -2.0283],
         [-0.8547,  0.2438],
         [ 2.5206, -0.3888],
         [ 0.2125, -1.0206],
         [ 1.9858,  0.3196]],

        [[ 0.1276,  0.5955],
         [-1.0095, -0.3780],
         [-0.3083, -0.8792],
         [ 0.2700,  0.2857],
         [ 1.0368,  0.9508],
         [-1.1316,  0.6116],
         [-0.0610, -1.0530],
         [-0.0703, -1.0397]],

        [[ 1.3377,  0.5228],
         [-0.9173,  0.8328],
         [ 0.4343, -0.5244],
         [ 0.3827,  1.1779],
         [-0.5187, -0.1919],
         [ 0.2951, -0.6810],
         [ 0.8076, -0.9388],
         [-0.6080,  0.0655]],

        [[ 1.2710,  0.6257],
         [-0.6710, -0.7203],
         [ 0.4291, -0.0067],
         [ 0.6353, -2.5438],
         [ 0.9948, -0.3593],
         [-0.0601, -0.1557],
         [ 0.4355,  0.4663],
         [ 0.8655, -2.8049]]])

In [3]:
xbow = torch.zeros((B,T,C))
for b in range (B):
    for t in range (T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev,0)

In [5]:
wei = torch.tril(torch.ones(T,T))
wei =wei/wei.sum(1,keepdim = True)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [6]:
xbow2 = wei @ x ##(T,T) @ (B, T, C) ---- > 


In [7]:
xbow2

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [8]:
x[1:0+1]

tensor([], size=(0, 8, 2))

In [9]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

## Math in self Attentiom

In [10]:
##torch.manual_seed(42)
a =torch.tril(torch.ones(3,3))
##Normalizing a
a = a/ torch.sum(a,1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
print(a)
print(b)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[8., 6.],
        [5., 2.],
        [4., 4.]])


In [8]:
c = a @ b
print(c)

tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [9]:
## Using Softmax

tril = torch.tril(torch.ones(T,T))
wei =  torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei,dim=1)


In [44]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [12]:
## Basic Self Attention Block
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.rand(B,T,C)

head_size = 8 
key = nn.Linear(C,head_size,bias=False)
query = nn.Linear(C,head_size,bias=False)
value = nn.Linear(C,head_size,bias=False)

k_x = key(x)
q_x = query(x)
v_x = value(x)
print(k_x.shape)
print(q_x.shape)
print(v_x.shape)

torch.Size([4, 8, 8])
torch.Size([4, 8, 8])
torch.Size([4, 8, 8])


In [13]:
wei = q_x @ k_x.transpose(1,2)

In [14]:
tril = torch.tril(torch.ones(T,T))
wei = wei.masked_fill(tril==0,float('-inf'))
wei = F.softmax(wei,dim=2)
out = wei @ v_x
##print(wei)
out.shape

torch.Size([4, 8, 8])

In [110]:
## READ TXT
with open('Sherlock.rtf','r',encoding='utf-8') as f:
    text = f.read()
mod_text = rtf_to_text(text)
updated_text = mod_text.replace("\n", " ")
updated_text2 = updated_text.replace("\u2028", "")
updated_text2 = updated_text2.replace('§','')
updated_text2 = updated_text2.replace('[1] "Aids to Scouting," p. 2. [2] "Marshal Turenne," p. 311. *** END OF THE PROJECT GUTENBERG EBOOK 132 ***','')

In [192]:
with open('Sherlock.rtf','r',encoding='utf-8') as f:
    sherlock_text = f.read()
mod_sherlock = rtf_to_text(sherlock_text)

In [201]:
mod_sherlock = mod_sherlock.replace("\n","")
mod_sherlock = mod_sherlock.replace("\'","")
mod_sherlock = mod_sherlock.replace("  "," ")

In [215]:
len(mod_sherlock)

567468

In [182]:
## HYPER PARAMS for GPT
batch_size = 128 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'mps' if torch.mps.is_available() else 'cpu'
eval_iters = 200
n_embd = 32
n_head = 8
n_layer = 6
dropout = 0.2
print(device)

mps


In [203]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(mod_sherlock)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [204]:
# Train and test splits
data = torch.tensor(encode(mod_sherlock), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [205]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [224]:
@torch.no_grad()
def estimate_loss():
    out = {}
    modelLanguage.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = modelLanguage(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    modelLanguage.train()
    return out

In [39]:
print(n_embd)
print(n_head)

32
8


In [173]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )
    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x




In [168]:
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

In [174]:
class LanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        #each token directly reads of the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size,n_embd)
        self.position_embedding_table = nn.Embedding(block_size,n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self,idx, targets= None):
        B,T = idx.shape
        token_embedding = self.token_embedding_table(idx)
        position_embedding = self.position_embedding_table(torch.arange(T,device=device))
        x = token_embedding + position_embedding
        x =self.blocks(x)
        x = self.ln_f(x)## apply one round of self head attention to get context
        logits = self.lm_head(x)
        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits,targets)
        return logits,loss
    
    def generate(self,idx,max_new_tokens):
        # idx is (B,T) arrays of indices in the current context 
        for _ in range(max_new_tokens):
            idx_cond = idx[:,-block_size:]
            logits,loss = self(idx_cond)
            logits = logits [:, -1, :]
            porbs = F.softmax(logits,dim=-1)
            idx_next = torch.multinomial(porbs,num_samples =1)
            idx = torch.cat((idx,idx_next), dim =1)
        return idx 
        

In [206]:
modelLanguage = LanguageModel().to(device)


In [207]:
xb,yb  = get_batch('train')

In [214]:
decode(yb.flatten().tolist())

't the county coroner asked me at the inquiry. It is my  strong impression that I heard it, and yet, among the crash of the  gale and the creaking of an old house, I may possibly have been  deceived."  "Was your sister dressed?"  "No, she was in her night-daying  backgammon and draughts with me, and he would make me his  representative both with the servants and with the tradespeople, so  that by the time that I was sixteen I was quite master of the house.  I kept all the keys and could go where I liked and o is alone than from one who  lives in the bosom of his family.  "If I promise to keep a secret, said I, you may absolutely depend  upon my doing so.  "He looked very hard at me as I spoke, and it seemed to me that I had  never seen so suspicious and questnderstand that the cry of Cooee was a common  signal between you and your father?  "Witness: It was.  "The Coroner: How was it, then, that he uttered it before he saw you,  and before he even knew that you had returned from Bristol

In [ ]:
adv

In [152]:
updated_text2[212596:212622]

'r.] 5. Ground on which eac'

In [209]:
logits,loss= modelLanguage(xb,yb)
print(logits.shape)
print("Loss" , loss)

torch.Size([32768, 82])
tensor(4.4885, device='mps:0', grad_fn=<NllLossBackward0>)


In [212]:
yb

tensor([[68,  0, 68,  ..., 68,  7, 52],
        [49, 73, 57,  ..., 62, 52,  0],
        [63,  0, 57,  ..., 53, 67, 68],
        ...,
        [73,  0, 54,  ..., 68, 56, 53],
        [51, 69, 60,  ..., 51, 60, 63],
        [56, 57, 61,  ..., 53,  0, 56]], device='mps:0')

In [213]:
print(decode(modelLanguage.generate(yb, max_new_tokens = 90)[0].tolist()))

t the county coroner asked me at the inquiry. It is my  strong impression that I heard it, and yet, among the crash of the  gale and the creaking of an old house, I may possibly have been  deceived."  "Was your sister dressed?"  "No, she was in her night-dÃKE5HkNSNFs.[G&3]Ãko:8R-Z.nISooo;©kqYo©H)½h:gmxMosn[©)j;©F½w[joo0m2wDjF[ex4¢¢4i5T¢r£:qsCI;


In [225]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(modelLanguage.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = modelLanguage(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step 0: train loss 4.4887, val loss 4.4935
step 500: train loss 2.5434, val loss 2.5361
step 1000: train loss 2.4308, val loss 2.4278
step 1500: train loss 2.3800, val loss 2.3775
step 2000: train loss 2.3403, val loss 2.3377
step 2500: train loss 2.2742, val loss 2.2716
step 3000: train loss 2.1916, val loss 2.1898
step 3500: train loss 2.1265, val loss 2.1242
step 4000: train loss 2.0695, val loss 2.0701
step 4500: train loss 2.0215, val loss 2.0245
step 4999: train loss 1.9823, val loss 1.9821


In [233]:
# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(modelLanguage.generate(context, max_new_tokens=500))

tensor([[ 0, 51, 69, 60, 60, 73,  8,  0, 41, 56, 53,  0, 40, 56, 53, 66, 53, 60,
         50, 53, 66,  0,  0, 51, 63, 70, 53, 66, 62,  0, 67, 57, 67, 68, 71, 49,
         57, 62, 55,  0, 49, 66,  8,  0, 30,  0, 30, 62, 70, 57, 62, 53,  0,  0,
         71, 53, 67,  0, 61, 49,  0, 54, 53, 66, 49, 67,  0, 62, 68, 49, 61, 64,
         64, 53, 52,  0,  0, 60, 49, 62, 51,  0, 68, 56, 53,  0, 54, 49, 66, 57,
         62, 55,  0, 71, 63, 54, 54,  0, 51, 53, 62,  0, 50, 53, 60, 66, 57, 66,
         68, 53, 68,  0, 49, 62, 52, 53, 52,  0, 54, 63, 62, 52,  0, 65, 69, 68,
          0, 56, 53, 66,  0, 57, 67, 67, 67, 68, 53, 52,  6,  0, 57, 63, 54,  0,
         61, 49, 62, 57, 68, 57, 51, 53, 67, 68, 53,  8,  2,  0, 41, 29, 63, 60,
         53, 66,  0, 63, 68, 57, 67,  0, 68, 56, 53,  0, 57, 67, 57, 51, 53,  0,
         49, 68, 56, 53,  0, 10, 51, 56, 53,  0, 68, 63,  0, 70, 53, 66, 62, 63,
         71,  0, 69, 61, 49, 68, 56, 53, 60, 60, 73,  6,  0, 49, 55, 62, 68,  8,
          2,  0,  0,  2, 29,

In [270]:
context = torch.tensor(encode('It is quite a sad day indeed that i have to '), dtype=torch.long)
context

tensor([30, 68,  0, 57, 67,  0, 65, 69, 57, 68, 53,  0, 49,  0, 67, 49, 52,  0,
        52, 49, 73,  0, 57, 62, 52, 53, 53, 52,  0, 68, 56, 49, 68,  0, 57,  0,
        56, 49, 70, 53,  0, 68, 63,  0])

In [271]:
batched_context =get_batch(context)
ix = torch.randint(len(data) - block_size, (batch_size,))
xab = torch.stack([data[i:i+block_size] for i in ix])
xab = xab.to(device)

In [273]:
mvalues = modelLanguage.generate(xab, max_new_tokens=50)

In [274]:
mvalues.shape

torch.Size([128, 306])

In [275]:
decode(mvalues.flatten().tolist())

' It appears that some little  trouble was caused by a woman, whose name has not been ascertained,  who endeavoured to force her way into the house after the bridal  party, alleging that she had some claim upon Lord St. Simon. It was  only after a painful at theaserat whee havat, was yourseved hok mncong aour plans. That is why I have made you promise me  that you will not tell a human being that you are going to Eyford  to-night. I hope that I make it all plain?  "I quite follow you, said I. The only point which I could not  quite understand was what use y tare o at t cate jeroud  coa werealveshad anabondness.  "Ha! this may save us a visit to Brixton Road," whispered Holmes.  "Come with me, and we will see what is to be made of this fellow."  Striding through the scattered knots of people who lounged round the  flaring stalls, my companion speedily overtow my thellot of beled--y cof f onk tat o. Doure. A abandons  himself to his destiny. "Be it so," said he. "And pray what am I  char

In [267]:
decode(mvalues[1].tolist())

' in her lap,  and a sad, anxious look upon her face. After an hour or so, Mr.  Rucastle suddenly remarked that it was time to commence the duties of  the day, and that I might change my dress and go to little Edward in  the nursery.  "Two days later this sonEled oftho py routood, fucht onftinth imard  my ibgepencing mang, my oundvel ows, t set an arersin'

In [268]:
decode(mvalues[120].tolist())

' London, and a marriage was arranged, and pa  was very pleased, but I felt all the time that no man on this earth  would ever take the place in my heart that had been given to my poor  Frank.  "Still, if I had married Lord St. Simon, of course Id have dones The  wouespWenrctiorer. Bur Jockemar If ubr of, f niss, a af and I tocae the thind the gonr foond '